version: '3.8'

services:
   
  consumer:
    container_name: consumer
    image: consumer
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["go" , "run", "cmd/consumer/main.go"]
    platform: linux/amd64
    ports:
      - "8080:8080" 
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  api:
    container_name: api
    image: api
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["go" , "run", "cmd/api/main.go"]
    platform: linux/amd64
    ports:
      - "8081:8081" 
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  producer:
    container_name: producer
    image: producer
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["go" , "run", "cmd/producer/main.go"]
    platform: linux/amd64
    ports:
      - "8082:8082" 
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: legacy   
    ports:
      - "5432:5432"
    volumes:
      - my-db:/var/lib/postgres
      - "./scripts/postgresql_scripts.sql:/docker-entrypoint-initdb.d/postgresql_scripts.sql"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
      - "./scripts/mysql_scripts.sql:/docker-entrypoint-initdb.d/mysql_scripts.sql"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka:
    image: confluentinc/cp-server:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_COMMAND_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_REPLICATION_FACTOR: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_STREAMS_REPLICATION_FACTOR: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_STREAMS_REPLICATION_FACTOR: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_STREAMS_REPLICATION_FACTOR: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_STREAMS_REPLICATION_FACTOR: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_STREAMS_REPLICATION_FACTOR: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_STREAMS_REPLICATION_FACTOR: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_STREAMS_REPLICATION_FACTOR: 1
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

volumes:
  my-db: